(() => {
'use strict';
const B = window.Bulletin;
const KEY = 'tayninh-bantin-workflow-v2', ROLE_KEY = KEY + '-role', BACKUP_KEY = KEY + '-before-reset';
const $ = selector => document.querySelector(selector);
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const icons = {
 grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h5"/>',
 check:'<path d="m8 12 3 3 8-9"/><path d="M20 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h11"/>',
 book:'<path d="M12 5v16M3 3h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5v17h-5a4 4 0 0 0-4 1 4 4 0 0 0-4-1H3z"/>',
 chart:'<path d="M4 3v18h18M9 16v-5M14 16V6M19 16v-8"/>',
 people:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.9"/><circle cx="9" cy="7" r="4"/><path d="M16 3a4 4 0 0 1 0 8"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 search:'<circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 shield:'<path d="m12 3 9 4v5c0 5-9 10-9 10S3 17 3 12V7zM8 12l3 3 5-5"/>',
 repeat:'<path d="m17 2 4 4-4 4M3 11V8a2 2 0 0 1 2-2h16M7 22l-4-4 4-4m14-1v3a2 2 0 0 1-2 2H3"/>',
 send:'<path d="m22 2-7 20-4-9-9-4 20-7ZM11 13l11-11"/>',
 eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.file}</svg>`;
const fmt = value => { const d = new Date(value?.length === 10 ? value + 'T12:00:00' : value); return isNaN(d) ? '—' : new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d); };
const shortDate = value => fmt(value).slice(0,5);
const badge = (status, label) => `<span class="badge badge-${escape(status)}">${escape(label || B.statuses[status] || B.results[status] || status)}</span>`;
const person = id => state.people.find(p => p.id === id);
const button = (label, action, id='', style='btn', ico='') => `<button type="button" class="${style}" data-action="${escape(action)}"${id ? ` data-id="${escape(id)}"` : ''}>${ico ? icon(ico) : ''}${escape(label)}</button>`;
const phaseEmpty = (title, text='') => `<div class="empty">${icon('file')}<strong>${escape(title)}</strong>${text ? `<p>${escape(text)}</p>` : ''}</div>`;
let storageWarning = '', state;
try { const stored = JSON.parse(localStorage.getItem(KEY) || 'null'); state = stored?.schema === 2 && Array.isArray(stored.articles) && Array.isArray(stored.people) && Array.isArray(stored.issues) ? stored : B.seed(); }
catch { state = B.seed(); storageWarning = 'Không đọc được dữ liệu đã lưu. Đang hiển thị bộ hồ sơ mẫu.'; }
let actorKey = 'secretary';
try { const saved = localStorage.getItem(ROLE_KEY); if (saved) { B.actorInfo(state,saved); actorKey=saved; } } catch {}
let actor = B.actorInfo(state,actorKey), page = 'overview', filter = '', search = '', toastTimer, lastFocused, fileDatabase;
const pageLabels = { overview:'Tổng quan', articles:'Bài viết', reviews:'Phản biện', issues:'Số bản tin', reports:'Báo cáo', roles:'Vai trò & quy trình' };
const allowedPages = () => actor.role === 'leader' ? ['overview','reports','roles'] : actor.role === 'reviewer' ? ['overview','articles','reviews','roles'] : actor.role === 'author' ? ['overview','articles','reports','roles'] : Object.keys(pageLabels);
function toast(message) { clearTimeout(toastTimer); $('#toast').textContent=message; $('#toast').classList.add('show'); toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200); }
function commit(next) { try { localStorage.setItem(KEY, JSON.stringify(next)); } catch { throw new Error('Trình duyệt chưa cho phép lưu hoặc đã hết dung lượng. Kết quả chưa được lưu.'); } state=next; }
function transition(type,payload,message) { commit(B.apply(state,actor,type,payload)); closeModal(); render(); toast(message); }
function roleOptions() {
 $('#role').innerHTML = `<optgroup label="Biên tập"><option value="secretary">Thư ký biên tập</option></optgroup><optgroup label="Người nộp bài">${state.people.filter(p=>p.role==='author').map(p=>`<option value="${escape(p.id)}">Người nộp · ${escape(p.name)}</option>`).join('')}</optgroup><optgroup label="Người phản biện">${state.people.filter(p=>p.role==='reviewer').map(p=>`<option value="${escape(p.id)}">${escape(p.name)}</option>`).join('')}</optgroup><optgroup label="Xem số liệu"><option value="chief">Trưởng Ban biên tập</option><option value="deputy">Phó Ban biên tập</option></optgroup>`;
 $('#role').value=actorKey;
}
function scoped() { return actor.role==='leader' ? state.articles : B.visibleArticles(state,actor); }
function projected() { return B.visibleArticles(state,actor).map(a=>B.projectArticle(a,actor)); }
function pendingReviews() { return scoped().flatMap(a=>['reviewing','results'].includes(a.status) ? B.activeReviews(a).filter(r=>!r.result && (actor.role!=='reviewer'||r.reviewerId===actor.id)).map(r=>({a,r})) : []); }
function overdue() { return pendingReviews().filter(x=>x.r.due<B.date()); }
function header(kicker,title,description,action='') { return `<div class="page-header"><div><span class="eyebrow">${escape(kicker)}</span><h1>${escape(title)}</h1><p>${escape(description)}</p></div>${action}</div>`; }
function stat(label,value,note,ico,good=false) { return `<div class="stat"><span class="stat-icon">${icon(ico)}</span><span class="stat-label">${escape(label)}</span><strong class="stat-number">${escape(value)}</strong><span class="stat-note ${good?'good':''}">${escape(note)}</span></div>`; }
function statsBlock() {
 const list=scoped(), count=s=>list.filter(a=>a.status===s).length;
 if (actor.role==='reviewer') { const assigned=list.flatMap(a=>a.reviews.filter(r=>r.reviewerId===actor.id)); return `<div class="stats">${stat('Hồ sơ được giao',list.length,'Chỉ các bài thuộc phân công','file')}${stat('Chờ đánh giá',pendingReviews().length,'Phiên bản được giao hiện tại','clock')}${stat('Đã gửi kết quả',assigned.filter(r=>r.result).length,'Các lượt đánh giá đã hoàn tất','check',true)}${stat('Quá hạn',overdue().length,'Theo hạn của từng lượt giao','calendar')}</div>`; }
 return `<div class="stats">${stat(actor.role==='author'?'Bài đã nộp':'Tổng bài tiếp nhận',list.length,actor.role==='author'?'Hồ sơ của người nộp hiện tại':'Bộ hồ sơ đang theo dõi','file')}${stat('Đang phản biện',count('reviewing')+count('results'),'Theo dõi từng lượt đánh giá','people')}${stat('Cần chỉnh sửa',count('revision'),'Chờ tiếp nhận phiên bản mới','repeat')}${stat('Đạt / đã đăng',count('approved')+count('published'),`${count('approved')} bài đạt · ${count('published')} bài đã đăng`,'check',true)}</div>`;
}
function articleTable(list,compact=false) {
 if (!list.length) return phaseEmpty('Chưa có hồ sơ phù hợp','Thay đổi điều kiện tìm kiếm hoặc chuyển vai trò để xem bộ hồ sơ tương ứng.');
 const secretary=actor.role==='secretary', reviewer=actor.role==='reviewer';
 return `<div class="table-wrap"><table><thead><tr><th>Bài viết / hồ sơ</th>${secretary&&!compact?'<th class="optional-col">Người nộp</th>':''}<th>Trạng thái</th>${!compact?`<th class="optional-col">${reviewer?'Hạn phản biện':'Tiến độ'}</th>`:''}<th></th></tr></thead><tbody>${list.map(a=>{
  const rr=a.reviews.filter(r=>r.version===a.version), own=rr.find(r=>r.reviewerId===actor.id), done=rr.filter(r=>r.result).length;
  let progress=reviewer ? own?`${fmt(own.due)}${own.result?`<span class="subline">${B.results[own.result]}</span>`:''}`:'Lượt trước đã kết thúc' : secretary&&rr.length ? `${done}/${rr.length} kết quả<div class="progress-mini"><i style="width:${Math.round(done/rr.length*100)}%"></i></div>`:`<span class="muted">Phiên bản ${String(a.version).padStart(2,'0')}</span>`;
  return `<tr><td><button class="article-link" data-action="detail" data-id="${escape(a.id)}">${escape(a.title)}</button><span class="subline">${escape(a.code)} <span aria-hidden="true">·</span> ${escape(a.category)}</span></td>${secretary&&!compact?`<td class="optional-col"><div class="person-row"><span class="avatar">${escape(a.authorName.slice(-2))}</span><span>${escape(a.authorName)}<small class="subline">${escape(a.agency)}</small></span></div></td>`:''}<td>${badge(a.status)}</td>${!compact?`<td class="optional-col">${progress}</td>`:''}<td><button class="icon-btn" data-action="detail" data-id="${escape(a.id)}" aria-label="Xem hồ sơ ${escape(a.code)}">${icon('arrow')}</button></td></tr>`;
 }).join('')}</tbody></table></div>`;
}
function attentionPanel() {
 let entries=[];
 if(actor.role==='secretary') {
  const sub=state.articles.filter(a=>a.status==='submitted'), results=state.articles.filter(a=>a.status==='results');
  if(overdue().length) entries.push({ico:'clock',title:`${overdue().length} lượt phản biện quá hạn`,sub:'Kiểm tra tiến độ người được phân công',action:'nav-reviews'});
  if(sub.length) entries.push({ico:'file',title:`${sub.length} bài chờ sơ duyệt`,sub:'Kiểm tra nội dung và tệp bản thảo',action:'nav-articles'});
  if(results.length) entries.push({ico:'check',title:`${results.length} bài chờ tổng hợp`,sub:'Đã đủ kết quả từ người phản biện',action:'nav-articles'});
  if(!entries.length) entries.push({ico:'check',title:'Các hồ sơ đã được xử lý',sub:'Tiếp tục theo dõi tiến độ và số bản tin',action:'nav-issues'});
 } else if(actor.role==='author') {
  entries=scoped().filter(a=>a.status==='revision').map(a=>({ico:'repeat',title:'Yêu cầu bổ sung bản sửa',sub:a.code,action:'detail',id:a.id}));
  if(!entries.length) entries.push({ico:'file',title:'Theo dõi bản thảo đã nộp',sub:'Trạng thái cập nhật theo từng bước xử lý',action:'nav-articles'});
 } else if(actor.role==='reviewer') {
  entries=pendingReviews().slice(0,3).map(({a,r})=>({ico:'clock',title:a.code,sub:`Hạn xử lý ${fmt(r.due)}${r.due<B.date()?' · Quá hạn':''}`,action:'detail',id:a.id}));
  if(!entries.length) entries.push({ico:'check',title:'Đã hoàn tất các lượt được giao',sub:'Theo dõi kết quả đã gửi trong hồ sơ',action:'nav-reviews'});
 }
 return `<section class="panel"><div class="panel-head"><div><h2>Việc cần theo dõi</h2><p>Ưu tiên trong vai trò hiện tại</p></div>${icon('clock')}</div><div class="panel-body">${entries.map((x,i)=>`<div class="attention-item"><span class="attention-icon ${i?'blue':''}">${icon(x.ico)}</span><div><strong>${escape(x.title)}</strong><small>${escape(x.sub)}</small>${button('Mở danh sách →',x.action,x.id||'','text-btn')}</div></div>`).join('')}</div></section>`;
}
function processStrip() { return `<div class="process-strip">${[['01','Nộp bài','Người nộp bản thảo'],['02','Sơ duyệt','Thư ký kiểm tra'],['03','Phản biện','Một hoặc nhiều người'],['04','Tổng hợp','Đạt hoặc trả bản sửa'],['05','Đăng bản tin','Sau khi đạt yêu cầu']].map(x=>`<div class="process-step"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</div>`; }
function distribution(list=scoped()) {
 const colors={submitted:'#d5b37b',ready:'#a4b5c6',reviewing:'#759db2',results:'#a49abb',revision:'#d39a83',approved:'#84ac96',published:'#577d8c'};
 return Object.entries(B.statuses).map(([s,label])=>{const n=list.filter(a=>a.status===s).length;return `<div class="chart-row"><div class="chart-title"><span>${escape(label)}</span><strong>${n} bài</strong></div><div class="chart-bar"><i style="width:${list.length?n/list.length*100:0}%;background:${colors[s]}"></i></div></div>`;}).join('');
}
function leaderOverview() {
 const pending=pendingReviews(), a=state.articles;
 return `${header('BAN BIÊN TẬP','Toàn cảnh bản tin','Số liệu tổng hợp và tiến độ xử lý. Chế độ chỉ xem, không có thao tác nghiệp vụ.',button('Xem báo cáo','nav-reports','','btn','chart'))}<div class="hero"><div><span class="eyebrow">${escape(actor.name)}</span><h2>Nắm tiến độ.<br>Theo dõi chất lượng biên tập.</h2><p>Tiếp nhận, phản biện và phát hành trong cùng một bảng số liệu.</p></div><div class="hero-stamp"><strong>${String(a.length).padStart(2,'0')}</strong>HỒ SƠ<span>ĐANG THEO DÕI</span></div></div>${statsBlock()}<div class="layout-two"><section class="panel"><div class="panel-head"><div><h2>Phân bố trạng thái</h2><p>Số liệu từ bộ hồ sơ dùng thử</p></div>${icon('chart')}</div><div class="panel-body">${distribution()}</div></section><section class="panel"><div class="panel-head"><h2>Chỉ số điều hành</h2>${badge('published','Chỉ xem')}</div><div class="panel-body"><div class="metric"><span>Lượt phản biện đang xử lý</span><strong>${pending.length}</strong></div><div class="metric"><span>Lượt quá hạn</span><strong>${overdue().length}</strong></div><div class="metric"><span>Bài chờ tổng hợp</span><strong>${a.filter(a=>a.status==='results').length}</strong></div><div class="metric"><span>Số bản tin đã phát hành</span><strong>${state.issues.filter(x=>x.published).length}</strong></div><div class="note" style="margin-top:22px">Trưởng/Phó Ban biên tập xem số liệu, thống kê; không tham gia nộp bài, sơ duyệt hoặc phản biện.</div></div></section></div>${processStrip()}`;
}
function overview() {
 if(actor.role==='leader') return leaderOverview();
 const roles={secretary:['BÀN LÀM VIỆC BIÊN TẬP','Tổng quan bản tin','Theo dõi tiến độ bài viết, kết quả phản biện và kế hoạch phát hành.'],author:['KHÔNG GIAN NGƯỜI NỘP BÀI','Bản thảo & tiến độ','Nộp bài, nhận ý kiến tổng hợp và bổ sung các phiên bản chỉnh sửa.'],reviewer:['KHÔNG GIAN PHẢN BIỆN','Hồ sơ được phân công','Đánh giá độc lập trên bản thảo ẩn danh. Chỉ xem hồ sơ được giao.']};
 const r=roles[actor.role], list=projected().slice().sort((a,b)=>b.created.localeCompare(a.created)).slice(0,5);
 const primary=actor.role==='author'?button('Nộp bài mới','submit','','btn btn-primary','plus'):button('Xem quy trình','guide','','btn','arrow');
 return `${header(...r,primary)}<div class="hero"><div><span class="eyebrow">TIẾP NHẬN · PHẢN BIỆN · BIÊN TẬP</span><h2>Trọn quy trình.<br>Rõ từng bước xử lý.</h2><p>${actor.role==='reviewer'?'Danh tính tác giả được tách khỏi nội dung và tệp dùng để phản biện.':actor.role==='author'?'Mỗi phiên bản được lưu trong hồ sơ, cùng tiến độ xử lý và yêu cầu bổ sung.':'Một bài có thể giao nhiều người phản biện. Ý kiến chưa đạt được tổng hợp để tiếp nhận bản sửa.'}</p></div><div class="hero-stamp"><strong>${String(scoped().length).padStart(2,'0')}</strong>HỒ SƠ<span>TRONG VAI TRÒ HIỆN TẠI</span></div></div>${statsBlock()}<div class="layout-two"><section class="panel"><div class="panel-head"><div><h2>${actor.role==='reviewer'?'Bài viết được giao':'Hồ sơ đang theo dõi'}</h2><p>Trạng thái xử lý và phiên bản hiện tại</p></div>${button('Xem tất cả →','nav-articles','','text-btn')}</div>${articleTable(list,true)}<div class="table-foot">${actor.role==='reviewer'?'Đánh giá độc lập · Không hiển thị tên tác giả và nhận xét của người phản biện khác':'Lịch sử xử lý được ghi nhận trong từng hồ sơ'}</div></section>${attentionPanel()}</div>${processStrip()}`;
}
function articles() {
 const title=actor.role==='reviewer'?'Bài viết được giao':actor.role==='author'?'Bài viết của người nộp':'Quản lý bài viết';
 return `${header('HỒ SƠ & PHIÊN BẢN',title,actor.role==='reviewer'?'Chỉ bản thảo ẩn danh thuộc phân công hiện tại hoặc lịch sử được giao.':'Theo dõi từ sơ duyệt, phản biện đến chỉnh sửa và đăng bản tin.',actor.role==='author'?button('Nộp bài mới','submit','','btn btn-primary','plus'):'')}<section class="panel"><div class="filters"><div class="search">${icon('search')}<input id="article-search" aria-label="Tìm bài viết" placeholder="Tìm tên bài hoặc mã hồ sơ…" value="${escape(search)}"></div><select id="article-filter" aria-label="Lọc trạng thái"><option value="">Tất cả trạng thái</option>${Object.entries(B.statuses).map(([s,label])=>`<option value="${s}"${s===filter?' selected':''}>${escape(label)}</option>`).join('')}</select><span class="filter-total">${projected().length} hồ sơ</span></div><div id="articles-table">${articleList()}</div></section>${actor.role==='reviewer'?`<div class="split-note">${icon('shield')}<p>Chỉ hiển thị nội dung và tệp ẩn danh. Tên người nộp, đơn vị công tác và tệp bản thảo gốc không xuất hiện trong màn hình phản biện.</p></div>`:''}`;
}
function articleList() { const all=projected(), term=search.trim().toLocaleLowerCase('vi'), list=all.filter(a=>(!filter||a.status===filter)&&(!term||`${a.title} ${a.code}`.toLocaleLowerCase('vi').includes(term))); return articleTable(list)+`<div class="table-foot">Hiển thị ${list.length} / ${all.length} hồ sơ trong vai trò hiện tại</div>`; }
function reviews() {
 const rows=scoped().flatMap(a=>a.reviews.filter(r=>r.version===a.version&&(actor.role!=='reviewer'||r.reviewerId===actor.id)).map(r=>({a:B.projectArticle(a,actor),r})));
 return `${header('ĐÁNH GIÁ ĐỘC LẬP','Theo dõi phản biện','Một hồ sơ, nhiều lượt đánh giá. Mỗi người phản biện có kết quả và thời hạn riêng.',actor.role==='secretary'?button('Thêm người phản biện','reviewer-add','','btn','plus'):'')}${actor.role==='reviewer'?statsBlock():`<div class="stats">${stat('Tổng lượt giao',rows.length,'Phiên bản hiện tại của hồ sơ','people')}${stat('Đang xử lý',pendingReviews().length,'Các lượt chưa gửi kết quả','clock')}${stat('Đã có kết quả',rows.filter(x=>x.r.result).length,'Thư ký tổng hợp độc lập','check',true)}${stat('Quá hạn',overdue().length,'Hạn xử lý chưa hoàn tất','calendar')}</div>`}<section class="panel"><div class="panel-head"><div><h2>${actor.role==='reviewer'?'Lượt phản biện của vai trò hiện tại':'Danh sách phân công'}</h2><p>${actor.role==='reviewer'?'Kết quả độc lập, gửi về thư ký biên tập':'Theo dõi kết quả của từng người được giao'}</p></div>${badge('reviewing','Bản thảo ẩn danh')}</div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Bài viết</th>${actor.role==='secretary'?'<th>Người phản biện</th>':''}<th>Hạn xử lý</th><th>Kết quả</th><th></th></tr></thead><tbody>${rows.map(({a,r})=>`<tr><td><button class="article-link" data-action="detail" data-id="${escape(a.id)}">${escape(a.title)}</button><span class="subline">${escape(a.code)} · Phiên bản ${r.version}</span></td>${actor.role==='secretary'?`<td><strong>${escape(person(r.reviewerId)?.name)}</strong><small class="subline">${escape(person(r.reviewerId)?.specialty)}</small></td>`:''}<td class="nowrap">${fmt(r.due)}</td><td>${r.result?badge(r.result):['reviewing','results'].includes(a.status)?badge(r.due<B.date()?'revise':'reviewing',r.due<B.date()?'Quá hạn':'Đang thực hiện'):badge('ready','Lượt đã kết thúc')}</td><td>${button(actor.role==='reviewer'&&!r.result&&a.status==='reviewing'?'Đánh giá':'Xem hồ sơ',actor.role==='reviewer'&&!r.result&&a.status==='reviewing'?'review':'detail',a.id,'btn btn-small')}</td></tr>`).join('')}</tbody></table></div>`:phaseEmpty('Chưa có lượt phân công')}</section><div class="note">Kết quả <strong>Cần chỉnh sửa</strong> hoặc <strong>Không đạt</strong> được chuyển về thư ký để tổng hợp. Người nộp nhận ý kiến tổng hợp, không nhận danh tính người phản biện.</div>`;
}
function issues() {
 return `${header('BIÊN TẬP & PHÁT HÀNH','Số bản tin','Xếp bài đạt phản biện vào số, sắp thứ tự và ghi nhận phát hành trong bản dùng thử.',button('Tạo số bản tin','issue-edit','','btn btn-primary','plus'))}<div class="issues">${state.issues.slice().reverse().map(x=>`<article class="panel issue-card"><div class="issue-cover"><div><span class="eyebrow">TRƯỜNG CHÍNH TRỊ TỈNH TÂY NINH</span><h3>${escape(x.title)}</h3></div><strong>${escape(x.number)}</strong></div><div class="issue-meta">${badge(x.published?'published':'ready',x.published?'Đã phát hành':'Đang biên tập')}<span>${x.articleIds.length} bài · ${fmt(x.date)}</span></div><ol class="issue-list">${x.articleIds.map((id,i)=>{const a=state.articles.find(a=>a.id===id);return a?`<li><span>${String(i+1).padStart(2,'0')}</span><button class="article-link" data-action="detail" data-id="${escape(a.id)}">${escape(a.title)}</button></li>`:'';}).join('')||'<li><span>Chưa có bài trong mục lục.</span></li>'}</ol><div class="issue-actions">${button(x.published?'Xem mục lục':'Biên tập mục lục','issue-edit',x.id,'btn btn-small',x.published?'book':'file')}${!x.published?button('Phát hành số','issue-publish',x.id,'btn btn-small btn-navy','send'):''}</div></article>`).join('')}</div>`;
}
function reports() {
 const list=scoped(), total=list.length, authors=actor.role==='author';
 const categories=['Đào tạo, bồi dưỡng','Nghiên cứu, trao đổi','Thực tiễn cơ sở'];
 return `${header('SỐ LIỆU & THỐNG KÊ',authors?'Tiến độ bài đã nộp':'Báo cáo tổng hợp',authors?'Thống kê các hồ sơ thuộc người nộp hiện tại.':'Tổng hợp tình trạng tiếp nhận, phản biện và số bản tin.',button('Tải báo cáo CSV','csv','','btn','download'))}${statsBlock()}<div class="layout-two"><section class="panel"><div class="panel-head"><div><h2>Trạng thái bài viết</h2><p>Thống kê theo bộ hồ sơ hiện tại</p></div><span class="muted" style="font-size:10px">${total} hồ sơ</span></div><div class="panel-body">${distribution(list)}</div></section><section class="panel"><div class="panel-head"><h2>${authors?'Tỷ lệ hoàn thành':'Chuyên mục & tiến độ'}</h2>${icon('chart')}</div><div class="panel-body">${categories.map(c=>`<div class="metric"><span>${c}</span><strong>${list.filter(a=>a.category===c).length}</strong></div>`).join('')}<div class="metric"><span>Bài đạt hoặc đã đăng</span><strong>${total?Math.round(list.filter(a=>['approved','published'].includes(a.status)).length/total*100):0}%</strong></div>${!authors?`<div class="metric"><span>Lượt phản biện quá hạn</span><strong>${overdue().length}</strong></div><div class="metric"><span>Số bản tin đã phát hành</span><strong>${state.issues.filter(x=>x.published).length}</strong></div>`:''}<div class="note" style="margin-top:21px">${actor.role==='leader'?'Chế độ chỉ xem số liệu. Không hiển thị tệp bản thảo, ý kiến đánh giá hoặc thao tác xử lý hồ sơ.':'Số liệu cập nhật sau mỗi thao tác được lưu trên trình duyệt này.'}</div></div></section></div>`;
}
function flow() { return `<div class="flow-board"><div class="flow-node"><span class="eyebrow">01 · TIẾP NHẬN</span><h3>Nộp bài & sơ duyệt</h3><p>Người nộp gửi bản thảo. Thư ký kiểm tra; bài chưa đạt được trả lại kèm ý kiến.</p></div><div class="flow-node"><span class="eyebrow">02 · ĐÁNH GIÁ ĐỘC LẬP</span><h3>Giao nhiều người phản biện</h3><p>Thư ký chuẩn bị bản ẩn danh, chọn người phản biện và hạn xử lý riêng.</p><div class="review-lanes"><span>Phản biện 01</span><span>Phản biện 02</span><span>Phản biện …</span></div></div><div class="flow-node"><span class="eyebrow">03 · HOÀN TẤT</span><h3>Tất cả đạt → đăng</h3><p>Thư ký xác nhận đủ kết quả đạt của phiên bản hiện tại, xếp vào số và đăng bản dùng thử.</p></div></div><div class="loop-band"><strong>Chưa đạt → tiếp nhận bản sửa</strong><br>Kết quả và ý kiến → thư ký tổng hợp → người nộp chỉnh sửa → sơ duyệt lại → phân công lại. Kết quả cũ được giữ trong lịch sử, không dùng để duyệt phiên bản mới.</div>`; }
function permissionTable() { return `<div class="table-wrap"><table class="role-table"><thead><tr><th>Vai trò</th><th>Được xem</th><th>Được thao tác</th></tr></thead><tbody><tr><td><strong>Người nộp bài</strong></td><td>Hồ sơ của mình, tiến độ và ý kiến tổng hợp</td><td class="allowed">Nộp bài; bổ sung bản sửa khi có yêu cầu</td></tr><tr><td><strong>Thư ký</strong></td><td>Danh tính tác giả, bản gốc, kết quả của các phản biện</td><td class="allowed">Sơ duyệt; chuẩn bị bản ẩn danh; phân công; tổng hợp; biên tập và đăng</td></tr><tr><td><strong>Phản biện 01, 02, …</strong></td><td>Bản ẩn danh được giao và nhận xét của mình</td><td class="allowed">Đánh giá độc lập, gửi kết quả về thư ký</td></tr><tr><td><strong>Trưởng/Phó Ban biên tập</strong></td><td>Số liệu, tiến độ và thống kê tổng hợp</td><td class="readonly">Chỉ xem; không xử lý nghiệp vụ</td></tr></tbody></table></div>`; }
function roles() {
 return `${header('TỔ CHỨC QUY TRÌNH','Vai trò & cách xử lý','Mỗi vai trò có phạm vi hồ sơ và công việc riêng.') }<section class="panel"><div class="panel-head"><div><h2>Quy trình biên tập bài viết</h2><p>Nhiều phản biện độc lập, một đầu mối tổng hợp</p></div>${icon('repeat')}</div><div class="panel-body">${flow()}</div></section><section class="panel"><div class="panel-head"><h2>Phạm vi theo vai trò</h2>${badge('ready','Chọn ở góc trên')}</div>${permissionTable()}<div class="panel-body" style="padding-top:18px"><div class="note">Bản dùng thử cho phép chuyển vai trò để xem toàn bộ quy trình. Dữ liệu và tệp chỉ lưu trên trình duyệt đang sử dụng; không đồng bộ giữa các thiết bị. Việc ẩn danh nội dung và tệp cần được thư ký kiểm tra trước khi giao phản biện.</div></div></section>${actor.role==='secretary'?`<section class="panel"><div class="panel-head"><div><h2>Quản lý bản dùng thử</h2><p>Khôi phục bộ hồ sơ minh họa khi cần thử lại từ đầu</p></div></div><div class="setting-actions">${button('Khôi phục dữ liệu mẫu','reset','','btn','repeat')}${button('Hoàn tác lần khôi phục','undo-reset','','btn')}${button('Xuất dữ liệu hồ sơ','backup','','btn','download')}</div><div class="panel-body"><small class="muted">Tệp xuất chứa thông tin hồ sơ, phiên bản và kết quả; không chứa tệp đính kèm.</small></div></section>`:''}`;
}
function render() {
 if(!allowedPages().includes(page))page='overview';
 roleOptions();
 const labels={...pageLabels,articles:actor.role==='reviewer'?'Bài được giao':actor.role==='author'?'Bài đã nộp':'Bài viết'};
 const navIcons={overview:'grid',articles:'file',reviews:'check',issues:'book',reports:'chart',roles:'people'};
 $('#navigation').innerHTML=allowedPages().map(p=>`<button class="nav-item ${page===p?'active':''}" data-page="${p}"${page===p?' aria-current="page"':''}>${icon(navIcons[p])}<span>${labels[p]}</span>${p==='articles'?`<span class="nav-count">${projected().length}</span>`:''}</button>`).join('');
 $('#breadcrumb').textContent=labels[page];
 $('#content').innerHTML=(storageWarning?`<div class="note warm notice-storage">${escape(storageWarning)}</div>`:'')+({overview,articles,reviews,issues,reports,roles}[page]());
}
function navigate(p) { if(!allowedPages().includes(p))return; closeModal(); page=p;render(); window.scrollTo({top:0,behavior:'instant'}); }
function modal(title,body,kicker='KHÔNG GIAN BIÊN TẬP') {
 lastFocused=document.activeElement;
 $('#dialog-title').textContent=title;$('#dialog-kicker').textContent=kicker;$('#dialog-content').innerHTML=body;
 if(!$('#dialog').open)$('#dialog').showModal();
}
function closeModal() { if($('#dialog').open){$('#dialog').close();if(lastFocused?.isConnected)lastFocused.focus();} }
const form = (type,id,body,submitLabel='Lưu kết quả',extra='') => `<form data-form="${type}" data-id="${escape(id||'')}" ${extra}><div class="modal-body">${body}</div><div class="form-error" role="alert"></div><div class="modal-footer">${button('Hủy','close','','btn')}<button type="submit" class="btn btn-primary">${escape(submitLabel)}</button></div></form>`;
const textField=(label,name,value='',required=true,placeholder='')=>`<label class="field">${escape(label)}${required?' *':''}<input name="${name}" value="${escape(value)}" ${required?'required':''} placeholder="${escape(placeholder)}" maxlength="300"></label>`;
const textarea=(label,name,value='',min=10)=>`<label class="field">${escape(label)} *<textarea name="${name}" required minlength="${min}" maxlength="6000">${escape(value)}</textarea></label>`;
function fileField(anonymous=false) { return `<div class="field">${anonymous?'Tệp đã ẩn danh':'Tệp bản thảo'}<div class="file-field"><input type="file" name="attachment" aria-label="${anonymous?'Chọn tệp ẩn danh':'Chọn tệp bản thảo'}" accept=".doc,.docx,.pdf"><label class="check-line"><input type="checkbox" name="sample" checked>Dùng tệp mẫu nếu chưa chọn tệp đính kèm</label></div><small>DOC, DOCX hoặc PDF · Tối đa 10 MB · Lưu trên trình duyệt hiện tại.</small></div>`; }
function showSubmit() {
 if(actor.role!=='author')return;
 modal('Nộp bài viết mới',form('submit','',`${textField('Tên bài viết','title') }<div class="form-grid">${textField('Người nộp','author',actor.name,false)}<label class="field">Chuyên mục *<select name="category"><option>Đào tạo, bồi dưỡng</option><option>Nghiên cứu, trao đổi</option><option>Thực tiễn cơ sở</option></select></label></div>${textField('Đơn vị công tác','agency',actor.agency||'',false)}${textarea('Tóm tắt nội dung','text','',40)}${fileField()}<div class="note">Bài gửi thử được lưu trên trình duyệt này. Chuyển sang vai trò Thư ký để thực hiện sơ duyệt.</div>`,'Gửi bài thử'),'TIẾP NHẬN BẢN THẢO');
 $('#dialog-content input[name=author]').readOnly=true;
}
function downloadCard(a,file,label,kind,version) { return `<div class="file-card">${icon('file')}<div><strong>${escape(file.name)}</strong><small>${escape(label)}${file.sample?' · Tệp minh họa':''}</small></div>${button('Tải tệp','download-file',a.id,'text-btn','download').replace('data-action="download-file"',`data-action="download-file" data-kind="${kind}" data-version="${version}"`)}</div>`; }
function showDetail(id) {
 const source=state.articles.find(a=>a.id===id), a=source&&B.projectArticle(source,actor);if(!a){toast('Hồ sơ không thuộc vai trò hiện tại.');return;}
 const reviewer=actor.role==='reviewer', secretary=actor.role==='secretary', own=a.reviews.find(r=>r.version===a.version&&r.reviewerId===actor.id);
 let content=`${badge(a.status)}<div class="summary-grid"><div><small>Mã hồ sơ</small><strong>${escape(a.code)}</strong></div><div><small>Phiên bản hiện tại</small><strong>Bản ${String(a.version).padStart(2,'0')}</strong></div><div><small>Chuyên mục</small>${escape(a.category)}</div>${!reviewer?`<div><small>Người nộp</small>${escape(a.authorName)}</div><div><small>Đơn vị</small>${escape(a.agency)}</div><div><small>Tiếp nhận</small>${fmt(a.created)}</div>`:''}</div>`;
 if(reviewer)content+=`<div class="note">Bản thảo ẩn danh · Kết quả được gửi riêng về thư ký. Không hiển thị danh tính tác giả hoặc nhận xét của người phản biện khác.</div>`;
 content+=`<section class="detail-section"><h3>${reviewer?'Nội dung dùng cho phản biện':'Tóm tắt bản thảo'}</h3><p>${escape(reviewer?a.anonymous?.text||'Phiên bản mới đang được chuẩn bị; nội dung sẽ xuất hiện sau khi được phân công lại.':a.text)}</p></section>`;
 if(!reviewer)content+=`<section class="detail-section"><h3>Phiên bản bản thảo</h3>${a.versions.slice().reverse().map(v=>downloadCard(a,v.file,`Bản ${v.number} · ${fmt(v.created)}`,'original',v.number)).join('')}</section>`;
 if((reviewer||secretary)&&a.anonymous)content+=`<section class="detail-section"><h3>Tệp phản biện đã ẩn danh</h3>${downloadCard(a,a.anonymous.file,`Bản ${a.anonymous.version} · Đã xác nhận kiểm tra`,'anonymous',a.anonymous.version)}</section>`;
 if((reviewer||secretary)&&a.reviews.length)content+=`<section class="detail-section"><h3>${reviewer?'Kết quả đã gửi':'Các lượt phản biện'}</h3>${a.reviews.slice().sort((x,y)=>y.version-x.version).map(r=>`<div class="review-card"><header><div><strong style="font-size:11px">${reviewer?'Lượt phản biện của vai trò hiện tại':escape(person(r.reviewerId)?.name)}</strong><small class="subline">Phiên bản ${r.version} · Hạn ${fmt(r.due)}</small></div>${r.result?badge(r.result):badge('reviewing',r.version===a.version&&a.status==='reviewing'?'Chờ kết quả':'Lượt đã kết thúc')}</header>${r.comment?`<p class="comment">${escape(r.comment)}</p>`:''}</div>`).join('')}</section>`;
 if(!reviewer&&a.feedback.length)content+=`<section class="detail-section"><h3>Ý kiến gửi người nộp</h3>${a.feedback.slice().reverse().map(f=>`<div class="feedback-box"><small>Phiên bản ${f.version} · ${fmt(f.at)}</small><p>${escape(f.text)}</p></div>`).join('')}</section>`;
 if(!reviewer)content+=`<section class="detail-section"><h3>Lịch sử xử lý</h3><ul class="timeline">${a.history.slice().reverse().map(h=>`<li>${escape(h.text)}<time>${fmt(h.at)}</time></li>`).join('')}</ul></section>`;
 let actions='';
 if(secretary){
  if(a.status==='submitted')actions+=button('Sơ duyệt bài viết','screen',id,'btn btn-primary','check');
  if(a.status==='ready')actions+=button('Chuẩn bị & phân công','assign',id,'btn btn-primary','people');
  if(['reviewing','results'].includes(a.status)&&B.activeReviews(source).some(r=>['reject','revise'].includes(r.result)))actions+=button('Tổng hợp & trả bản sửa','return',id,'btn btn-primary','repeat');
  if(a.status==='results'&&B.allPass(source))actions+=button('Xác nhận đạt phản biện','approve',id,'btn btn-primary','check');
  if(a.status==='approved')actions+=button('Đăng bài thử','publish',id,'btn btn-primary','send');
 }
 if(actor.role==='author'&&a.status==='revision')actions+=button('Nộp bản chỉnh sửa','resubmit',id,'btn btn-primary','repeat');
 if(reviewer&&own&&!own.result&&a.status==='reviewing')actions+=button('Gửi đánh giá','review',id,'btn btn-primary','check');
 content+=`<div class="action-row">${actions}</div>`;
 modal(a.title,`<div class="modal-body">${content}</div>`,'CHI TIẾT HỒ SƠ');
}
function showScreen(id) { const a=state.articles.find(a=>a.id===id); if(actor.role!=='secretary'||a?.status!=='submitted')return; modal('Sơ duyệt bài viết',form('screen',id,`<div class="note"><strong>${escape(a.code)}</strong> · ${escape(a.title)}</div><div class="form-radios"><label class="radio-label"><input name="decision" type="radio" value="pass" checked>Đạt, chuyển phân công</label><label class="radio-label"><input name="decision" type="radio" value="return">Chưa đạt, trả bổ sung</label></div><label class="field">Ý kiến sơ duyệt<textarea name="note" placeholder="Ghi rõ yêu cầu bổ sung khi trả bài…" maxlength="5000"></textarea></label>`,'Lưu sơ duyệt'),'KIỂM TRA BẢN THẢO'); }
function showAssign(id) {
 const a=state.articles.find(a=>a.id===id);if(actor.role!=='secretary'||a?.status!=='ready')return;
 modal('Chuẩn bị bản ẩn danh & phân công',form('assign',id,`<div class="note warm">Kiểm tra tên tác giả, đơn vị, lời cảm ơn, bình luận và metadata của tệp. Nội dung không được tự động bảo đảm đã ẩn danh.</div><div style="height:18px"></div>${textField('Tiêu đề dùng cho phản biện','title',a.title)}${textarea('Nội dung dùng cho phản biện','text',a.text,40)}${fileField(true)}<label class="check-line"><input type="checkbox" name="checked" required>Đã kiểm tra tiêu đề, nội dung và tệp; bản phản biện không tiết lộ danh tính tác giả.</label><div style="height:12px"></div><span class="field">Người phản biện * · Chọn một hoặc nhiều người</span><div class="select-people">${state.people.filter(p=>p.role==='reviewer').map(p=>`<div class="select-person"><label class="check-line"><input type="checkbox" name="reviewerIds" value="${escape(p.id)}"><span>${escape(p.name)}<small>${escape(p.specialty)}</small></span></label><label class="field">Hạn xử lý<input type="date" name="due-${escape(p.id)}" aria-label="Hạn của ${escape(p.name)}" value="${B.offset(7)}" min="${B.date()}"></label></div>`).join('')}</div><div class="note">Thời hạn có thể đặt riêng cho từng người phản biện được chọn.</div>`,'Giao phản biện'),'PHẢN BIỆN ĐỘC LẬP');
}
function showReview(id) {
 const a=state.articles.find(a=>a.id===id), view=a&&B.projectArticle(a,actor), own=a&&B.activeReviews(a).find(r=>r.reviewerId===actor.id);
 if(actor.role!=='reviewer'||!view||!own||own.result||a.status!=='reviewing')return;
 modal('Gửi kết quả phản biện',form('review',id,`<div class="note"><strong>${escape(a.code)}</strong> · Phiên bản ${a.version} · Hạn ${fmt(own.due)}</div><section class="detail-section"><h3>${escape(view.title)}</h3><p>${escape(view.anonymous?.text)}</p>${view.anonymous?downloadCard(view,view.anonymous.file,'Tệp đã ẩn danh','anonymous',a.version):''}</section><span class="field">Kết quả đánh giá *</span><div class="form-radios">${Object.entries(B.results).map(([r,label],i)=>`<label class="radio-label"><input type="radio" name="result" value="${r}"${!i?' checked':''}>${label}</label>`).join('')}</div>${textarea('Nhận xét gửi thư ký','comment')}<div class="note">Nhận xét được gửi riêng về thư ký để tổng hợp. Sau khi gửi, lượt đánh giá này được ghi nhận hoàn tất.</div>`,'Gửi kết quả'),'BẢN THẢO ẨN DANH');
}
function showReturn(id) { const a=state.articles.find(a=>a.id===id);if(actor.role!=='secretary')return; modal('Tổng hợp ý kiến & trả bản sửa',form('return',id,`<div class="note"><strong>${escape(a.code)}</strong> · ${escape(a.title)}</div><section class="detail-section"><h3>Ý kiến đánh giá đã nhận</h3>${B.activeReviews(a).filter(r=>r.result).map(r=>`<div class="review-card"><strong style="font-size:11px">${escape(person(r.reviewerId)?.name)} · ${B.results[r.result]}</strong><p class="comment">${escape(r.comment)}</p></div>`).join('')}</section>${textarea('Ý kiến tổng hợp gửi người nộp','note')}<label class="check-line"><input type="checkbox" name="checked" required>Đã kiểm tra ý kiến tổng hợp không tiết lộ tên và danh tính người phản biện.</label>`,'Gửi yêu cầu chỉnh sửa'),'TỔNG HỢP QUA THƯ KÝ'); }
function showResubmit(id) { const a=state.articles.find(a=>a.id===id);if(actor.role!=='author'||a?.authorId!==actor.id||a.status!=='revision')return;modal('Nộp bản chỉnh sửa',form('resubmit',id,`<div class="note"><strong>${escape(a.code)}</strong> · Phiên bản tiếp theo: ${a.version+1}</div>${a.feedback.at(-1)?`<div class="feedback-box"><small>Yêu cầu bổ sung gần nhất</small><p>${escape(a.feedback.at(-1).text)}</p></div>`:''}<div style="height:18px"></div>${textarea('Nội dung bản sửa','text',a.text,40)}${fileField()}<div class="note">Bản sửa được chuyển lại thư ký để sơ duyệt và phân công phản biện cho phiên bản mới.</div>`,'Gửi bản chỉnh sửa'),'TIẾP NHẬN PHIÊN BẢN MỚI'); }
function showApprove(id) { if(actor.role!=='secretary')return;const a=state.articles.find(a=>a.id===id);modal('Xác nhận đạt phản biện',form('approve',id,`<div class="note"><strong>${escape(a.code)}</strong> · ${escape(a.title)}</div><section class="detail-section"><h3>Kết quả của phiên bản ${a.version}</h3>${B.activeReviews(a).map(r=>`<div class="metric"><span>${escape(person(r.reviewerId)?.name)}</span>${badge(r.result||'reviewing',r.result?B.results[r.result]:'Chưa có kết quả')}</div>`).join('')}</section><div class="note">Chỉ xác nhận khi tất cả người được giao đều đánh giá đạt cho phiên bản hiện tại.</div>`,'Xác nhận đạt'),'HOÀN TẤT TỔNG HỢP'); }
function showPublish(id) { if(actor.role!=='secretary')return;const a=state.articles.find(a=>a.id===id), issues=state.issues.filter(x=>!x.published&&(!a.issueId||a.issueId===x.id));modal('Đăng bài trong bản dùng thử',issues.length?form('publish',id,`<div class="note"><strong>${escape(a.code)}</strong> · ${escape(a.title)}</div><div style="height:18px"></div><label class="field">Số bản tin *<select name="issueId">${issues.map(x=>`<option value="${escape(x.id)}">${escape(x.number)} · ${escape(x.title)}</option>`).join('')}</select></label><div class="note">Ghi nhận đăng bài trong bản dùng thử. Chưa kết nối xuất bản lên website chính thức của trường.</div>`,'Xác nhận đăng bài'):`<div class="modal-body"><div class="note">Chưa có số bản tin đang biên tập phù hợp. Tạo số mới hoặc điều chỉnh mục lục trước khi đăng.</div><div class="action-row">${button('Tạo số bản tin','issue-edit','','btn btn-primary','plus')}</div></div>`,'BIÊN TẬP & ĐĂNG BÀI'); }
function showIssue(id) {
 if(actor.role!=='secretary')return;const issue=state.issues.find(x=>x.id===id);
 if(issue?.published){modal(`Mục lục số ${issue.number}`,`<div class="modal-body"><div class="note">Đã ghi nhận phát hành ngày ${fmt(issue.date)}.</div><ol class="issue-list">${issue.articleIds.map((id,i)=>{const a=state.articles.find(a=>a.id===id);return `<li><span>${String(i+1).padStart(2,'0')}</span><button class="article-link" data-action="detail" data-id="${escape(id)}">${escape(a?.title)}</button></li>`;}).join('')}</ol></div>`,'SỐ BẢN TIN ĐÃ PHÁT HÀNH');return;}
 const selected=issue?.articleIds||[], candidates=[...selected,...state.articles.filter(a=>a.status==='approved'&&(!a.issueId||a.issueId===issue?.id)&&!selected.includes(a.id)).map(a=>a.id)];
 modal(issue?`Biên tập số ${issue.number}`:'Tạo số bản tin',form('issue_save',id,`<div class="form-grid">${textField('Số bản tin','number',issue?.number||'') }<label class="field">Ngày dự kiến phát hành *<input type="date" name="date" value="${issue?.date||B.offset(7)}" required></label></div>${textField('Tên bản tin','title',issue?.title||'Thông tin lý luận và thực tiễn')}<span class="field">Chọn bài và sắp thứ tự mục lục</span><div id="issue-picks">${candidates.map(id=>{const a=state.articles.find(a=>a.id===id);return `<div class="issue-pick" data-pick="${escape(id)}"><input type="checkbox" name="articleIds" value="${escape(id)}" aria-label="Chọn ${escape(a.code)}"${selected.includes(id)?' checked':''}${a.status==='published'?' disabled':''}><span>${escape(a.title)}<small>${escape(a.code)} · ${B.statuses[a.status]}</small></span><button type="button" class="icon-btn" data-action="issue-up" data-id="${escape(id)}" aria-label="Đưa ${escape(a.code)} lên">↑</button><button type="button" class="icon-btn" data-action="issue-down" data-id="${escape(id)}" aria-label="Đưa ${escape(a.code)} xuống">↓</button></div>`;}).join('')||'<div class="note">Chưa có bài đạt phản biện để xếp vào số.</div>'}</div>`,'Lưu số bản tin'),'MỤC LỤC & KẾ HOẠCH');
}
function showIssuePublish(id) { if(actor.role!=='secretary')return;const issue=state.issues.find(x=>x.id===id);modal(`Phát hành số ${issue.number}`,form('issue_publish',id,`<div class="note"><strong>${escape(issue.title)}</strong> · ${issue.articleIds.length} bài</div><section class="detail-section"><h3>Điều kiện phát hành</h3><p>Tất cả bài trong mục lục phải đạt phản biện ở phiên bản hiện tại. Các bài được ghi nhận đã đăng trong bản dùng thử.</p></section>`,'Xác nhận phát hành'),'BIÊN TẬP & PHÁT HÀNH'); }
function openDatabase() { if(!fileDatabase)fileDatabase=new Promise((resolve,reject)=>{const request=indexedDB.open('tayninh-bantin-files-v2',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('Không mở được nơi lưu tệp trên trình duyệt.'));});return fileDatabase; }
async function fileStore(operation,key,value) {const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction('files',operation==='put'?'readwrite':'readonly'), store=tx.objectStore('files'),req=operation==='put'?store.put(value,key):store.get(key);let result;req.onsuccess=()=>{result=req.result;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(new Error('Chưa lưu được tệp. Kiểm tra dung lượng trình duyệt.'));tx.onabort=()=>reject(new Error('Thao tác lưu tệp bị gián đoạn.'));});}
async function collectFile(formElement) {
 const f=formElement.elements.attachment.files[0];
 if(!f){if(!formElement.elements.sample.checked)throw new Error('Chọn tệp đính kèm hoặc sử dụng tệp mẫu.');return {sample:true,ext:'txt',size:0};}
 const ext=f.name.split('.').at(-1).toLowerCase();if(!['doc','docx','pdf'].includes(ext)||f.size>10*1024*1024||f.size===0)throw new Error('Chọn tệp DOC, DOCX hoặc PDF có nội dung, tối đa 10 MB.');
 const key=crypto.randomUUID();await fileStore('put',key,f);return {key,name:f.name,ext,size:f.size,sample:false};
}
function saveDownload(blob,name) {const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function downloadFile(id,kind,version) {
 const a=state.articles.find(a=>a.id===id),view=a&&B.projectArticle(a,actor);if(!view)throw new Error('Tệp không thuộc phạm vi vai trò hiện tại.');
 let file,text;
 if(kind==='anonymous'&&['reviewer','secretary'].includes(actor.role)&&view.anonymous&&view.anonymous.version===Number(version)){file=view.anonymous.file;text=view.anonymous.text;}
 else if(kind==='original'&&['secretary','author'].includes(actor.role)){const v=view.versions.find(v=>v.number===Number(version));file=v?.file;text=v?.text;}
 if(!file)throw new Error('Tệp không thuộc phân công hoặc phiên bản được phép xem.');
 const blob=file.sample?new Blob([`${kind==='anonymous'?view.anonymous.title:view.title}\n${view.code} · Phiên bản ${version}\n\n${text}\n\nTỆP MINH HỌA TRONG BẢN DÙNG THỬ.`],{type:'text/plain;charset=utf-8'}):await fileStore('get',file.key);
 if(!blob)throw new Error('Tệp không còn trên trình duyệt này.');saveDownload(blob,file.name);
}
function exportCSV() {const list=scoped(),rows=[['Trạng thái','Số bài'],...Object.entries(B.statuses).map(([s,label])=>[label,list.filter(a=>a.status===s).length])];if(actor.role==='secretary')rows.push([],['Mã hồ sơ','Tên bài','Người nộp','Chuyên mục','Phiên bản','Trạng thái'],...list.map(a=>[a.code,a.title,a.authorName,a.category,a.version,B.statuses[a.status]]));const safe=v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};saveDownload(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),`bao-cao-ban-tin-${B.date()}.csv`);toast('Đã tải báo cáo theo phạm vi vai trò hiện tại.');}
async function handleForm(event) {
 const f=event.target;if(!f.matches('form[data-form]'))return;event.preventDefault();const submit=f.querySelector('button[type=submit]'),error=f.querySelector('.form-error');submit.disabled=true;error.classList.remove('visible');
 try {const data=new FormData(f),type=f.dataset.form;let p={id:f.dataset.id};
  for(const name of ['title','text','category','agency','decision','note','due','result','comment','issueId','number','date','specialty','name'])if(data.has(name))p[name]=data.get(name);
  p.checked=data.has('checked');
  if(['submit','assign','resubmit'].includes(type))p.file=await collectFile(f);
  if(type==='assign'){p.reviewerIds=data.getAll('reviewerIds');p.dueMap=Object.fromEntries(p.reviewerIds.map(id=>[id,data.get('due-'+id)]));}
  if(type==='issue_save'){p.issueId=f.dataset.id||null;p.articleIds=Array.from(f.querySelectorAll('input[name=articleIds]')).filter(el=>el.checked).map(el=>el.value);}
  if(type==='issue_publish')p.issueId=f.dataset.id;
  if(type==='reset'){try{localStorage.setItem(BACKUP_KEY,JSON.stringify(state));}catch{throw new Error('Chưa lưu được bản để hoàn tác.');}commit(B.seed());closeModal();render();toast('Đã khôi phục dữ liệu mẫu. Có thể hoàn tác tại Vai trò & quy trình.');return;}
  transition(type,p,{submit:'Đã tiếp nhận bài thử. Chuyển sang Thư ký để sơ duyệt.',screen:'Đã lưu kết quả sơ duyệt.',assign:'Đã giao bản ẩn danh cho các người phản biện được chọn.',review:'Đã gửi kết quả riêng về thư ký.',return:'Đã gửi yêu cầu chỉnh sửa cho người nộp.',resubmit:'Đã nộp phiên bản mới; chờ sơ duyệt lại.',approve:'Đã xác nhận đạt phản biện.',publish:'Đã ghi nhận đăng bài trong bản dùng thử.',issue_save:'Đã lưu mục lục và kế hoạch số bản tin.',issue_publish:'Đã phát hành số bản tin trong bản dùng thử.',reviewer_add:'Đã bổ sung người phản biện và chế độ trải nghiệm tương ứng.'}[type]||'Đã lưu thao tác.');
 } catch(e){error.textContent=e.message;error.classList.add('visible');submit.disabled=false;error.scrollIntoView({block:'nearest'});}
}
document.addEventListener('submit',handleForm);
document.addEventListener('click',async event=>{
 const target=event.target.closest('[data-page],[data-action]');if(!target)return;if(target.dataset.page){navigate(target.dataset.page);return;}const action=target.dataset.action,id=target.dataset.id;
 try {
  if(action.startsWith('nav-'))return navigate(action.slice(4));
  if(action==='close')return closeModal();
  if(action==='guide')return modal('Từ bài nộp đến số bản tin',`<div class="modal-body">${flow()}<div style="height:22px"></div>${permissionTable()}</div>`,'QUY TRÌNH BIÊN TẬP');
  const actions={detail:showDetail,submit:showSubmit,screen:showScreen,assign:showAssign,review:showReview,return:showReturn,resubmit:showResubmit,approve:showApprove,publish:showPublish,'issue-edit':showIssue,'issue-publish':showIssuePublish};
  if(actions[action])return actions[action](id);
  if(action==='reviewer-add'&&actor.role==='secretary')return modal('Bổ sung người phản biện',form('reviewer_add','',`${textField('Tên hiển thị','name','',true,'Ví dụ: Phản biện 04')}${textField('Chuyên môn','specialty','',false)}<div class="note">Người phản biện mới xuất hiện trong danh sách phân công và danh sách vai trò dùng thử.</div>`,'Thêm người phản biện'),'DANH SÁCH PHẢN BIỆN');
  if(action==='download-file')return await downloadFile(id,target.dataset.kind,target.dataset.version);
  if(action==='csv')return exportCSV();
  if(action==='issue-up'||action==='issue-down'){const row=target.closest('.issue-pick'),picks=row.parentElement;if(action==='issue-up'&&row.previousElementSibling)picks.insertBefore(row,row.previousElementSibling);if(action==='issue-down'&&row.nextElementSibling)picks.insertBefore(row.nextElementSibling,row);return;}
  if(action==='backup'&&actor.role==='secretary'){saveDownload(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`du-lieu-ban-tin-${B.date()}.json`);return toast('Đã xuất dữ liệu hồ sơ, không bao gồm tệp đính kèm.');}
  if(action==='reset'&&actor.role==='secretary')return modal('Khôi phục bộ dữ liệu mẫu',form('reset','',`<div class="note">Các thao tác trong bản dùng thử trên trình duyệt này sẽ được thay bằng bộ hồ sơ mẫu ban đầu. Trạng thái hiện tại được giữ lại để hoàn tác.</div>`,'Khôi phục dữ liệu mẫu'),'THỬ LẠI QUY TRÌNH');
  if(action==='undo-reset'&&actor.role==='secretary'){const previous=JSON.parse(localStorage.getItem(BACKUP_KEY)||'null');if(!previous||previous.schema!==2)throw new Error('Chưa có lần khôi phục để hoàn tác.');const current=state;commit(previous);localStorage.setItem(BACKUP_KEY,JSON.stringify(current));render();return toast('Đã hoàn tác lần khôi phục.');}
 } catch(e){toast(e.message);}
});
$('#role').addEventListener('change',event=>{actorKey=event.target.value;actor=B.actorInfo(state,actorKey);try{localStorage.setItem(ROLE_KEY,actorKey);}catch{}search='';filter='';closeModal();page='overview';render();toast(`Đang trải nghiệm: ${actor.name}`);});
$('#close-dialog').addEventListener('click',closeModal);
$('#dialog').addEventListener('click',event=>{if(event.target===event.currentTarget){const rect=$('#dialog').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeModal();}});
document.addEventListener('input',event=>{if(event.target.id==='article-search'){search=event.target.value;$('#articles-table').innerHTML=articleList();}});
document.addEventListener('change',event=>{if(event.target.id==='article-filter'){filter=event.target.value;$('#articles-table').innerHTML=articleList();}});
window.addEventListener('hashchange',()=>{if(location.hash==='#overview')navigate('overview');});
window.addEventListener('storage',event=>{if(event.key===KEY&&event.newValue){try{const updated=JSON.parse(event.newValue);if(updated.schema===2){state=updated;actor=B.actorInfo(state,actorKey);closeModal();render();toast('Dữ liệu được cập nhật từ tab khác trên cùng trình duyệt.');}}catch{}}});
render();
})();
